processing:
  frequency: 100



input_size: 12000
n_channels: 19

dataset:
  name: tub_abnormal
  train_edf_dir: '../../Dataset/tuh_eeg_abnormal/v3.0.1/edf/train/'
  train_label_dir: '../data/train_label_12000.csv'
  train_data_dir: '../data/seg_csv/train_12000/'
  
  val_edf_dir: '../../Dataset/tuh_eeg_abnormal/v3.0.1/edf/eval/'
  val_label_dir: '../data/eval_label_12000.csv'
  val_data_dir: '../data/seg_csv/eval_12000/'
  
  mean: [-0.84925363, -0.57970241, -0.84873335, -0.65943293, -0.42680256, -0.55692595,
  -0.68915349, -0.76090215, -0.81714699, -0.4305129, -0.90823503, -0.66544529,
  -1.0178982 , -0.65606002, -1.12267558, -0.55692305,
  -0.27457596, -0.47549457,  0.16019251]
  std: [131.48135945, 106.25727984, 124.03741234,  92.54006106,
       121.32491175,  91.33204798, 124.02669847,  98.37289956,
       121.19875962,  94.25380354, 124.27180189, 108.16782282,
       116.69246245,  91.69132988, 120.04684075,  90.20482523,
       122.40893776, 119.17286241, 122.06775861]
     
  
  classes:
    normal: 0
    abnormal: 1
#   root: './data'
  num_workers: 16
#   transform: basic
  shuffle: True
  
model:
  d_model: 256
  n_head: 1
  n_layer: 1
  

criterion:
  name: ce

optimizer:
  name: adamw
  init_lr: 0.001
  weight_decay: 0.0

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

warmup: 0

train:
  experiment: mnist_cnn_train
  warmup_steps: 10000
  n_epochs: 15
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200

tensorboard:
  runs_dir: '../runs/'

quantize:
  weight_bit: 32
  input_bit: 32

noise:
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0
  random_state: 42

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "../weights/"
  weights:
  model_comment: ""
  resume: 0
  restore_checkpoint: ""

# model:
#   name: "MZI_CLASS_CNN"
#   mode: "usv"
#   kernel_list: [64, 64]
#   kernel_size_list: [3, 3]
#   hidden_list: []
#   block_list: [8, 8, 8]
#   stride_list: [1, 1]
#   padding_list: [1, 1]
#   dilation_list: [1, 1]
#   pool_out_size: 5
#   decompose_alg: reck

debug:
  verbose: 1
